version: "3.8"
name: auto-scalar
services:
  host:
    container_name: auto-scalar
    build: .
    restart: always
    depends_on:
      - mysql
      - redis
      - prometheus
      - alert-manager
      - jaeger
    ports:
      - 8000:8000
    environment:
      - DB_URL=mysql://root:root@host.docker.internal/auto_scalar
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  mysql:
    container_name: mysql
    image: bitnami/mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=auto_scalar
    volumes:
      - ./data/mysql/:/var/lib/mysql
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/var/lib/redis
  
  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./metrics_service/configs/prometheus_config.yml:/etc/prometheus/prometheus.yml
      - ./metrics_service/configs/rules/low_resource_usage_rule.yml:/etc/prometheus/low_resource_usage_rule.yml
      - ./metrics_service/configs/rules/high_resource_usage_rule.yml:/etc/prometheus/high_resource_usage_rule.yml
      - ./metrics_service/configs/rules/instance_down_rule.yml:/etc/prometheus/instance_down_rule.yml
      - ./data/prometheus/:/etc/prometheus/data
  
  alert-manager:
    container_name: alert-manager
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ./metrics_service/configs/prometheus_alert_manager_config.yml:/etc/alertmanager/alertmanager.yml

  jaeger:
    container_name: jaeger
    image: rancher/mirrored-jaegertracing-all-in-one:1.60.0
    ports:
      - 14250:14250
      - 14268:14268
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 5775:5775
      - 5778:5778
      - 6831:6831
      - 6832:6832
      - 9411:9411