global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - instance_down_rule.yml
  - high_resource_usage_rule.yml
  - low_resource_usage_rule.yml


alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - host.docker.internal:9093


scrape_configs:
  - job_name: "monitor_servers"
    scrape_interval: 10s
    http_sd_configs:
      - url: "http://host.docker.internal:8000/services"
        refresh_interval: 10s