route:
  receiver: 'default-receiver'

  routes:
    - receiver: "clone-worker"
      matchers:
        - alertname="high_resource_usage"
    
    - receiver: "remove-worker"
      matchers:
        - alertname="low_resource_usage"
    
    - receiver: "alert-instance-down"
      matchers:
        - alertname="instance_down"

receivers:
  - name: "default-receiver"

  - name: "clone-worker"
    webhook_configs:
      - url: http://host.docker.internal:8000/workers/clone

  - name: "remove-worker"
    webhook_configs:
      - url: http://host.docker.internal:8000/workers/remove

  - name: "alert-instance-down"
    webhook_configs:
      - url: http://host.docker.internal:8000/workers/remove
    