"""empty message

Revision ID: cf8b1c038dd7
Revises: 60d888538c8c
Create Date: 2024-12-02 18:16:32.865305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8b1c038dd7'
down_revision: Union[str, None] = '60d888538c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('workers', sa.Column('is_cloned', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'workers', 'workers', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_column('workers', 'is_cloned')
    op.drop_column('workers', 'parent_id')
    # ### end Alembic commands ###
